#!/bin/sh
echo "🎨 Running Prettier..."
npm run format
if [ $? -ne 0 ]; then
  echo "❌ Formatting failed. Commit aborted."
  exit 1
fi

echo "🔍 Running Eslint..."
npm run lint
if [ $? -ne 0 ]; then
  echo "❌ Linting failed. Commit aborted."
  exit 1
fi

echo "✅ All checks passed!"